"""Seed the archive with a realistic corpus of past factory runs.

Deterministic (fixed seed) so the numbers in the UI are reproducible and can be
regenerated by anyone who clones the repo.
"""

from __future__ import annotations

import random
import time

from .engine import Precedent, Case, GateResult

random.seed(1042)

HOUR = 3600.0

# ---------------------------------------------------------------------------
# failure families the factory actually encounters
# ---------------------------------------------------------------------------

FAMILIES = [
    {
        "family": "F-03 slop-palette",
        "lane": "web",
        "narratives": [
            "taste tier 1 rejected the frontend: indigo primary #6366F1 declared outside the token system in tokens.css:{n}, Inter used with no paired display face in layout.tsx:{n}, and emoji standing in for icons in the status column",
            "design lint failed with three named tells — hardcoded indigo primary at tokens.css:{n}, unpaired Inter stack, emoji glyphs used as status icons",
            "tier 1 design lint: gate 3 indigo primary outside tokens, gate 11 default font stack unpaired, gate 17 emoji as icons in the table",
            "frontend variant tripped the slop detector: default indigo accent, bare Inter, emoji status column",
        ],
        "gates": lambda: [GateResult("taste.t1", False, 0.4, "3 named tells"),
                          GateResult("taste.t2", True, 1.0)],
        "fix": "tokenize the primary from scraped design DNA, pair the display face with a text face, replace emoji with a semantic StatusDot",
        "fix_kind": "resume-findings",
        "resolved": True,
        "importance": 0.45,
    },
    {
        "family": "F-11 thin-web bending",
        "lane": "hardware",
        "narratives": [
            "physics gate failed on web bending: sigma {v} MPa against an allowable of 172 MPa, factor of safety {f} below the 1.5 target for the briefed tip load",
            "bracket failed bending at the root — computed stress {v} MPa exceeds allowable, FoS {f}",
            "closed-form bending check rejected the part: {v} MPa vs 172 MPa allowable, FoS {f} under target",
            "web section too thin for the cantilever load; bending margin negative at FoS {f}",
        ],
        "gates": lambda: [GateResult("physics.bend", False, round(random.uniform(0.55, 0.95), 2), "sigma over allowable"),
                          GateResult("physics.shear", True, 3.9),
                          GateResult("physics.mass", True, 1.4)],
        "fix": "invert sigma = 6M/(b t^2) for t at FoS 1.5, patch web_thickness in bracket.py, regenerate and re-run the gates",
        "fix_kind": "algebra",
        "resolved": True,
        "importance": 0.7,
    },
    {
        "family": "F-19 contract-drift",
        "lane": "web",
        "narratives": [
            "contract conformance failed: the frontend calls /api/fleet/{n}/status which is not in api-contract.json, and the api lane exposes an extra route the contract never declared",
            "api-contract drift — frontend fetch targets an undeclared endpoint, api exposes /api/parts/bulk which is not in the contract",
            "conformance gate diffed both directions and found an extra route plus one missing endpoint",
        ],
        "gates": lambda: [GateResult("contract.conformance", False, 0.5, "extra + missing routes"),
                          GateResult("smoke.boot", True, 1.0)],
        "fix": "regenerate api-contract.json from the plan, resume both lanes with the diff attached, re-run conformance",
        "fix_kind": "resume-findings",
        "resolved": True,
        "importance": 0.6,
    },
    {
        "family": "F-24 stale-scrape",
        "lane": "data",
        "narratives": [
            "bolt table scrape is {n} minutes old, past the freshness ttl — refusing to certify the part without ground truth",
            "vendor scrape stale by {n} minutes; the margin solver has no current price or stock to select against",
            "scrape freshness exceeded ttl at {n} minutes, certification blocked",
        ],
        "gates": lambda: [GateResult("scrape.freshness", False, 0.3, "past ttl"),
                          GateResult("physics.bend", True, 1.62)],
        "fix": "re-run the bright data collector, confirm the schema key-diff is clean, then re-run the margin solver",
        "fix_kind": "resume-findings",
        "resolved": True,
        "importance": 0.55,
    },
    {
        "family": "F-31 selector-break",
        "lane": "data",
        "narratives": [
            "scraper returned rows missing the tensile_mpa and price keys after the vendor restructured its table markup",
            "schema key-diff detected {n} omitted fields — the vendor changed its DOM and the extractor silently returned partial rows",
            "collector output no longer matches the pinned schema; grade parsed but tensile and price are absent",
        ],
        "gates": lambda: [GateResult("scrape.schema", False, 0.45, "keys omitted"),
                          GateResult("scrape.freshness", True, 1.0)],
        "fix": "run scraper heal, verify the preview against the pinned schema before the human sees it, approve, commit the healed extractor",
        "fix_kind": "human",
        "resolved": True,
        "importance": 0.8,
    },
    {
        "family": "F-42 budget-overrun",
        "lane": "hardware",
        "narratives": [
            "airworthy configuration costs ${v} against a ${n} budget — physics passes but the brief's cost ceiling does not",
            "cheapest passing fastener puts the build ${v} over budget; escalating rather than shipping an unsafe part",
            "budget gate failed at ${v}: every bolt that clears FoS 1.5 is above the ceiling",
        ],
        "gates": lambda: [GateResult("budget.total", False, 0.85, "over ceiling"),
                          GateResult("physics.bend", True, 1.62)],
        "fix": "escalate to a human with the priced delta; on approval raise the ceiling and re-run bom_select",
        "fix_kind": "human",
        "resolved": True,
        "importance": 0.75,
    },
    {
        "family": "F-58 flaky-smoke",
        "lane": "web",
        "narratives": [
            "merged smoke boot timed out waiting for the dev server on port {n}; the build itself succeeded",
            "playwright hit on / timed out after {n} ms though npm run build passed cleanly",
        ],
        "gates": lambda: [GateResult("smoke.boot", False, 0.0, "timeout"),
                          GateResult("contract.conformance", True, 1.0)],
        "fix": "",
        "fix_kind": "none",
        "resolved": False,
        "importance": 0.3,
    },
]


def seed(db_path: str = "precedent.db", runs: int = 1284, now: float | None = None) -> Precedent:
    now = now or time.time()
    p = Precedent(db_path)
    if p.count():
        return p

    rid = 1
    for i in range(runs):
        fam = random.choices(FAMILIES, weights=[18, 26, 9, 22, 12, 8, 5])[0]
        n = random.randint(2, 480)
        v = round(random.uniform(96, 260), 1)
        f = round(random.uniform(0.55, 0.98), 2)
        narrative = random.choice(fam["narratives"]).format(n=n, v=v, f=f)
        age = random.random() ** 1.6 * 90 * 24 * HOUR      # skew recent
        p.record(Case(
            run_id="%04d" % rid,
            lane=fam["lane"],
            narrative=narrative,
            gates=fam["gates"](),
            fix=fam["fix"],
            fix_kind=fam["fix_kind"],
            resolved=fam["resolved"] and random.random() > 0.04,
            ts=now - age,
            importance=fam["importance"],
            family=fam["family"],
        ))
        rid += 1
    return p


if __name__ == "__main__":
    import os, sys
    path = sys.argv[1] if len(sys.argv) > 1 else "precedent.db"
    if os.path.exists(path):
        os.remove(path)
    t0 = time.time()
    p = seed(path)
    print("seeded %d cases in %.2fs -> %s (%.1f KB)"
          % (p.count(), time.time() - t0, path, os.path.getsize(path) / 1024))
